### ISSUE TITLE
[Feature Request] Coins & Level Profile

### ISSUE THREAD

**Issue by crashzk** [hallucinogenic/MatchMaking-Ranks-By-Points#1]
I wonder if it would be possible to put the **Coins & Level Profile** option.

## How it would work
The players would type `!coin` to choose a Coins, in the case would open a menu to show all coins. This menu I myself can edit, if I even want to put new coins when the CSGO launches them.

Another would be the command `!profile` ai could choose a Level Profile would open a menu too. With all Level Profile also, in case also put in a file so that you can edit if the CSGO throw some update in the Level Profile.

These options in case would have option of cvar, if you want to configure for only players with access to privileges have access to the commands.

**_OBS: Congratulations on the plugin and hope you continue with the incredible work on it, and on upgrades I would be more than happy to make a donation if it is to encourage you to make these changes._**

@hallucinogenic

**Comment by crashzk** [comment]
Any news? Would be willing to pay up to 5 to 10 euros / dollar to help with the incentive...

**Comment by luis-rei97** [comment]
I believe it's just spending money for nothing, since it exists publicly, a plugin which shows the coins and profile ranks (IMO).

**Comment by crashzk** [comment]
Yes, it has however all I found comes with the fake rank together, this causes the bug plugin, has moments that rank based on the points does not work, I myself have never managed to make both work together.

**[EDIT]**
I, this is me, I do not like to send several plugins to the server, I prefer to leave whatever I give in the same plugin. So from the suggestion, outside I think it will greatly improve your plugin.

In any case I will be opening again this issues, maybe in the future do not come. :)
