### ISSUE TITLE
HLstatsX support

### ISSUE THREAD

**Issue by lazhoroni** [hallucinogenic/MatchMaking-Ranks-By-Points#11]
hlstatsx Can you add support for version 1.6.19?

**Comment by luis-rei97** [comment]
I'll check the HLStatsX includes, to see if it can work properly. Maybe in the next version.

**Comment by lazhoroni** [comment]
Resources:
https://github.com/NomisCZ/hlstatsx-community-edition
https://bitbucket.org/Maverick_of_UC/hlstatsx-community-edition/downloads/

**Comment by lazhoroni** [comment]
This resource works smoothly at https://stats.not2easy.pro/hlstats.php?mode=players&game=csgo. Sample board web page: https://stats.not2easy.pro/
