### ISSUE TITLE
Instead of only checking rank during connect, make it every time you spawn

### ISSUE THREAD

**Issue by eyal282** [hallucinogenic/MatchMaking-Ranks-By-Points#12]
Title explains it, instead of just OnClientPostAdminCheck, add a "HookEvent" for player_spawn

Edit: oh, it works on player_death, know that in some gamemodes it's possible to gain points without deaths ( VIP Gamemode ) so please make sure you add it on player_spawn as well.

**Comment by luis-rei97** [comment]
Didn't know that VIP Gamemode would do that, but I'll make that in next version.
