### ISSUE TITLE
[Feature Request] Player can switch patents

### ISSUE THREAD

**Issue by crashzk** [hallucinogenic/MatchMaking-Ranks-By-Points#6]
It would be interesting in future updates to put option of the players to select the patents that they want when they arrived at the Global Elite patent.

## How it would work
Once the players have achieved the Global Elite patent the player could choose which patent he wants to put on their profile.

It would also be interesting if this option is only allowed for players with privileges, ie if the player has privileges and reach the Global Elite he can choose the patent, if the player does not have privileges he can not change the patent.

**Comment by luis-rei97** [comment]
Well, someone "made" the feature you want, or similar: https://github.com/diogooonair/CSGO---MatchMaking-ranks-with-rankme-support-and-prestige

For what i've seen, it's almost a copypaste of my MM Ranks, but it's what you want (and I believe it has errors)

**Comment by crashzk** [comment]
Thanks for the suggestion, in any case let open this issues for future, who knows you launch this update, thanks again. And of course, congratulations to the plugin! :)

**Comment by diogooonair** [comment]
Yeah it is basically your code with more functions. I m fixing bugs and adding freatures.

**Comment by diogooonair** [comment]
And no errors reported yet
